function mergeNavbar(){

html = '';
html += '    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">';
html += '      <!-- Sidebar - Brand -->';
html += '      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">';
html += '        <div class="sidebar-brand-icon rotate-n-15">';
html += '          <i class="fas fa-laugh-wink"></i>';
html += '        </div>';
html += '        <div class="sidebar-brand-text mx-3">Potencialize </div>';
html += '      </a>';
html += '      <!-- Divider -->';
html += '      <hr class="sidebar-divider my-0">';
html += '      <!-- Nav Item - Dashboard -->';
html += '      <li class="nav-item active">';
html += '        <a class="nav-link" href="index.html">';
html += '          <i class="fas fa-fw fa-tachometer-alt"></i>';
html += '          <span>Dashboard</span></a>';
html += '      </li>';
html += '      <!-- Divider -->';
html += '      <hr class="sidebar-divider">';
html += '      <!-- Heading -->';
html += '      <div class="sidebar-heading">';
html += '        Cadastros';
html += '      </div>';
html += '      <!--Sidebar do Candidato-->';
html += '      <li class="nav-item">';
html += '        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseCandidates" aria-e';xpanded="true" aria-controls="collapseCandidates">
html += '          <i class="fas fa-fw fa-users"></i>';
html += '          <span>Candidatos</span>';
html += '        </a>';
html += '        <div id="collapseCandidates" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSide';bar">
html += '          <div class="bg-white py-2 collapse-inner rounded">';
html += '            <h6 class="collapse-header">Candidatos</h6>';
html += '            <a class="collapse-item" href="buttons.html">Novo...</a>';
html += '            <a class="collapse-item" href="cards.html">Listar Candidatos</a>';
html += '          </div>';
html += '        </div>';
html += '      </li>';
html += '      <!--Sidebar da Empresa-->';
html += '      <li class="nav-item">';
html += '        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseCompany" aria-expa';nded="true" aria-controls="collapseCompany">
html += '          <i class="fas fa-fw fa-building"></i>';
html += '          <span>Empresas</span>';
html += '        </a>';
html += '        <div id="collapseCompany" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar';">
html += '          <div class="bg-white py-2 collapse-inner rounded">';
html += '            <h6 class="collapse-header">Empresas</h6>';
html += '            <a class="collapse-item" href="buttons.html">Nova...</a>';
html += '            <a class="collapse-item" href="cards.html">Listar Empresas</a>';
html += '          </div>';
html += '        </div>';
html += '      </li>';
html += '      <!--Sidebar da Empresa-->';
html += '      <li class="nav-item">';
html += '        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseVagas" aria-expand';ed="true" aria-controls="collapseVagas">
html += '          <i class="fas fa-fw fa-briefcase"></i>';
html += '          <span>Vagas</span>';
html += '        </a>';
html += '        <div id="collapseVagas" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">';
html += '          <div class="bg-white py-2 collapse-inner rounded">';
html += '            <h6 class="collapse-header">Vagas</h6>';
html += '            <a class="collapse-item" href="buttons.html">Nova...</a>';
html += '            <a class="collapse-item" href="cards.html">Listar Vagas</a>';
html += '            <a class="collapse-item" href="cards.html">Vagas Encerradas</a>';
html += '          </div>';
html += '        </div>';
html += '      </li>';
html += '      <!-- Divider -->';
html += '      <hr class="sidebar-divider">';
html += '      <!-- Heading -->';
html += '      <div class="sidebar-heading">';
html += '        Addons';
html += '      </div>';
html += '      <!-- Nav Item - Pages Collapse Menu -->';
html += '      <li class="nav-item">';
html += '        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expand';ed="true" aria-controls="collapsePages">
html += '          <i class="fas fa-fw fa-folder"></i>';
html += '          <span>Pages</span>';
html += '        </a>';
html += '        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar';">
html += '          <div class="bg-white py-2 collapse-inner rounded">';
html += '            <h6 class="collapse-header">Login Screens:</h6>';
html += '            <a class="collapse-item" href="login.html">Login</a>';
html += '            <a class="collapse-item" href="register.html">Register</a>';
html += '            <a class="collapse-item" href="forgot-password.html">Forgot Password</a>';
html += '            <div class="collapse-divider"></div>';
html += '            <h6 class="collapse-header">Other Pages:</h6>';
html += '            <a class="collapse-item" href="404.html">404 Page</a>';
html += '            <a class="collapse-item" href="blank.html">Blank Page</a>';
html += '          </div>';
html += '        </div>';
html += '      </li>';
html += '      <!-- Nav Item - Charts -->';
html += '      <li class="nav-item">';
html += '        <a class="nav-link" href="charts.html">';
html += '          <i class="fas fa-fw fa-chart-area"></i>';
html += '          <span>Charts</span></a>';
html += '      </li>';
html += '      <!-- Nav Item - Tables -->';
html += '      <li class="nav-item">';
html += '        <a class="nav-link" href="tables.html">';
html += '          <i class="fas fa-fw fa-table"></i>';
html += '          <span>Tables</span></a>';
html += '      </li>';
html += '      <!-- Divider -->';
html += '      <hr class="sidebar-divider d-none d-md-block">';
html += '      <!-- Sidebar Toggler (Sidebar) -->';
html += '      <div class="text-center d-none d-md-inline">';
html += '        <button class="rounded-circle border-0" id="sidebarToggle"></button>';
html += '      </div>';
html += '    </ul>';
html += '    <!-- End of Sidebar -->';
html += '    <!-- Content Wrapper -->';
html += '    <div id="content-wrapper" class="d-flex flex-column">';
html += '      <!-- Main Content -->';
html += '      <div id="content">';
html += '        <!-- Topbar -->';
html += '        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">';
html += '          <!-- Sidebar Toggle (Topbar) -->';
html += '          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">';
html += '            <i class="fa fa-bars"></i>';
html += '          </button>';
html += '          <!-- Topbar Search -->';
html += '          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"';>
html += '            <div class="input-group">';
html += '              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria';-label="Search" aria-describedby="basic-addon2">
html += '              <div class="input-group-append">';
html += '                <button class="btn btn-primary" type="button">';
html += '                  <i class="fas fa-search fa-sm"></i>';
html += '                </button>';
html += '              </div>';
html += '            </div>';
html += '          </form>';
html += '          <!-- Topbar Navbar -->';
html += '          <ul class="navbar-nav ml-auto">';
html += '            <!-- Nav Item - Search Dropdown (Visible Only XS) -->';
html += '            <li class="nav-item dropdown no-arrow d-sm-none">';
html += '              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="drop';down" aria-haspopup="true" aria-expanded="false">
html += '                <i class="fas fa-search fa-fw"></i>';
html += '              </a>';
html += '              <!-- Dropdown - Messages -->';
html += '              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="sea';rchDropdown">
html += '                <form class="form-inline mr-auto w-100 navbar-search">';
html += '                  <div class="input-group">';
html += '                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for...';" aria-label="Search" aria-describedby="basic-addon2">
html += '                    <div class="input-group-append">';
html += '                      <button class="btn btn-primary" type="button">';
html += '                        <i class="fas fa-search fa-sm"></i>';
html += '                      </button>';
html += '                    </div>';
html += '                  </div>';
html += '                </form>';
html += '              </div>';
html += '            </li>';
html += '            <!-- Nav Item - Alerts -->';
html += '            <li class="nav-item dropdown no-arrow mx-1">';
html += '              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="drop';down" aria-haspopup="true" aria-expanded="false">
html += '                <i class="fas fa-bell fa-fw"></i>';
html += '                <!-- Counter - Alerts -->';
html += '                <span class="badge badge-danger badge-counter">3+</span>';
html += '              </a>';
html += '              <!-- Dropdown - Alerts -->';
html += '              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-label';ledby="alertsDropdown">
html += '                <h6 class="dropdown-header">';
html += '                  Alerts Center';
html += '                </h6>';
html += '                <a class="dropdown-item d-flex align-items-center" href="#">';
html += '                  <div class="mr-3">';
html += '                    <div class="icon-circle bg-primary">';
html += '                      <i class="fas fa-file-alt text-white"></i>';
html += '                    </div>';
html += '                  </div>';
html += '                  <div>';
html += '                    <div class="small text-gray-500">December 12, 2019</div>';
html += '                    <span class="font-weight-bold">A new monthly report is ready to download!</span>';
html += '                  </div>';
html += '                </a>';
html += '                <a class="dropdown-item d-flex align-items-center" href="#">';
html += '                  <div class="mr-3">';
html += '                    <div class="icon-circle bg-success">';
html += '                      <i class="fas fa-donate text-white"></i>';
html += '                    </div>';
html += '                  </div>';
html += '                  <div>';
html += '                    <div class="small text-gray-500">December 7, 2019</div>';
html += '                    $290.29 has been deposited into your account!';
html += '                  </div>';
html += '                </a>';
html += '                <a class="dropdown-item d-flex align-items-center" href="#">';
html += '                  <div class="mr-3">';
html += '                    <div class="icon-circle bg-warning">';
html += '                      <i class="fas fa-exclamation-triangle text-white"></i>';
html += '                    </div>';
html += '                  </div>';
html += '                  <div>';
html += '                    <div class="small text-gray-500">December 2, 2019</div>';
html += '                    Spending Alert: We've noticed unusually high spending for your account.';
html += '                  </div>';
html += '                </a>';
html += '                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>';
html += '              </div>';
html += '            </li>';
html += '            <!-- Nav Item - Messages -->';
html += '            <li class="nav-item dropdown no-arrow mx-1">';
html += '              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dr';opdown" aria-haspopup="true" aria-expanded="false">
html += '                <i class="fas fa-envelope fa-fw"></i>';
html += '                <!-- Counter - Messages -->';
html += '                <span class="badge badge-danger badge-counter">7</span>';
html += '              </a>';
html += '              <!-- Dropdown - Messages -->';
html += '              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-label';ledby="messagesDropdown">
html += '                <h6 class="dropdown-header">';
html += '                  Message Center';
html += '                </h6>';
html += '                <a class="dropdown-item d-flex align-items-center" href="#">';
html += '                  <div class="dropdown-list-image mr-3">';
html += '                    <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">';
html += '                    <div class="status-indicator bg-success"></div>';
html += '                  </div>';
html += '                  <div class="font-weight-bold">';
html += '                    <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've'; been having.</div>
html += '                    <div class="small text-gray-500">Emily Fowler · 58m</div>';
html += '                  </div>';
html += '                </a>';
html += '                <a class="dropdown-item d-flex align-items-center" href="#">';
html += '                  <div class="dropdown-list-image mr-3">';
html += '                    <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">';
html += '                    <div class="status-indicator"></div>';
html += '                  </div>';
html += '                  <div>';
html += '                    <div class="text-truncate">I have the photos that you ordered last month, how would you li';ke them sent to you?</div>
html += '                    <div class="small text-gray-500">Jae Chun · 1d</div>';
html += '                  </div>';
html += '                </a>';
html += '                <a class="dropdown-item d-flex align-items-center" href="#">';
html += '                  <div class="dropdown-list-image mr-3">';
html += '                    <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">';
html += '                    <div class="status-indicator bg-warning"></div>';
html += '                  </div>';
html += '                  <div>';
html += '                    <div class="text-truncate">Last month's report looks great, I am very happy with the progr';ess so far, keep up the good work!</div>
html += '                    <div class="small text-gray-500">Morgan Alvarez · 2d</div>';
html += '                  </div>';
html += '                </a>';
html += '                <a class="dropdown-item d-flex align-items-center" href="#">';
html += '                  <div class="dropdown-list-image mr-3">';
html += '                    <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">';
html += '                    <div class="status-indicator bg-success"></div>';
html += '                  </div>';
html += '                  <div>';
html += '                    <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me th';at people say this to all dogs, even if they aren't good...</div>
html += '                    <div class="small text-gray-500">Chicken the Dog · 2w</div>';
html += '                  </div>';
html += '                </a>';
html += '                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>';
html += '              </div>';
html += '            </li>';
html += '            <div class="topbar-divider d-none d-sm-block"></div>';
html += '            <!-- Nav Item - User Information -->';
html += '            <li class="nav-item dropdown no-arrow">';
html += '              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdo';wn" aria-haspopup="true" aria-expanded="false">
html += '                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>';
html += '                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">';
html += '              </a>';
html += '              <!-- Dropdown - User Information -->';
html += '              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDro';pdown">
html += '                <a class="dropdown-item" href="#">';
html += '                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>';
html += '                  Profile';
html += '                </a>';
html += '                <a class="dropdown-item" href="#">';
html += '                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>';
html += '                  Settings';
html += '                </a>';
html += '                <a class="dropdown-item" href="#">';
html += '                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>';
html += '                  Activity Log';
html += '                </a>';
html += '                <div class="dropdown-divider"></div>';
html += '                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">';
html += '                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>';
html += '                  Logout';
html += '                </a>';
html += '              </div>';
html += '            </li>';
html += '          </ul>';
html += '        </nav>';
html += '        <!-- End of Topbar -->';
html += '';

document.getElementById("sidebar-merge").innerHTML = html;
}
